
drop table highway.REFERENTIEL_TIERS;
drop table highway.PERSONNEMORALETIERS;
drop table highway.MEDECINTIERS;
drop table highway.ENTREPRISE;
drop table highway.ADRESSE;
drop table highway.TELEPHONE;
drop table highway.COMPTEURFACTURE;

create table highway.REFERENTIEL_TIERS (
	TIERSID VARCHAR(100) not null,
	IDENTIFIANTFONCTIONNEL VARCHAR(20),
	NOMCOURT VARCHAR(20),
	ADRESSEID VARCHAR(20),
	RIBID VARCHAR(20),
	TYPETIERS VARCHAR(20),
	primary key (TIERSID)
);

create table highway.PERSONNEMORALETIERS (
	NOMPOSTALLIGNE1 VARCHAR(20),
	NOMPOSTALLIGNE2 VARCHAR(20),
	NOM VARCHAR(20),
	TIERSID VARCHAR(20) not null REFERENCES highway.REFERENTIEL_TIERS(TIERSID)
);

create table highway.MEDECINTIERS (
	TIERSID VARCHAR(100) not null REFERENCES highway.PERSONNEMORALETIERS(TIERSID),
	NUMEROADELI VARCHAR(20),
	TYPETITRE VARCHAR(20),
	TYPECATEGORIE VARCHAR(20),
	TYPESPECIALITE VARCHAR(20),
	DATEDEBUTAGREMENT Date,
	DATEFINAGREMENT Date,
	TYPECIVILITE VARCHAR(20),
	ACCEPTEEXPERTISES BOOLEAN,
	ACCEPTECONTREVISITES BOOLEAN,
	NOMBREKMMAXIMUM INTEGER(5),
	TYPEETAT VARCHAR(20),
	DATEINSCRIPTION Date,
	DATEMANDATEMENT Date,
	DATENONUTILISABLE Date,
	DATEDERNIEREMAJLISTEDDASS Date
);
create table highway.ADRESSE (
	ADRESSEID VARCHAR(20),
	COMPLEMENTREMISE VARCHAR(20),
	TYPEVOIE VARCHAR(20),
	NOMVOIE VARCHAR(20),
	COMPLEMENT VARCHAR(20),
	BOITEPOSTALE VARCHAR(20),
	CODEPOSTAL VARCHAR(20),
	LIBELLEACHEMINEMENT VARCHAR(20),
	TYPEPAYS VARCHAR(20),
	AFFICHERLOCALITE BOOLEAN,
	OBSERVATIONSADRESSE VARCHAR(20)
);
create table highway.COMPTEURFACTURE (
	DOMAINE VARCHAR(20),
	COMPTEUR INT,
	DATEDERNIEREFACTURE DATE
);
create table highway.ENTREPRISE (
	TIERSID VARCHAR(100) not null REFERENCES highway.PERSONNEMORALETIERS(TIERSID),
	NUMEROSIRET VARCHAR(20),
	CODENAF VARCHAR(20),
	ISDANSGROUPEDEXIASOFAXIS VARCHAR(20),
	CONVENTIONCOLLECTIVE VARCHAR(20),
	NOMBRESALARIES Date,
	NUMEROURSSAF Date,
	TYPESOCIETE VARCHAR(20),
	ETABID VARCHAR(20),
	NUMEROASSOCIATION BOOLEAN,
	DATEPUBLICATIONASSOCIATION BOOLEAN
);
create table highway.TELEPHONE (
	TELEPHONEID VARCHAR(20),
	VALEUR VARCHAR(20),
	DESCRIPTION VARCHAR(20),
	TYPETELEPHONE VARCHAR(20),
	primary key (TELEPHONEID)
);
commit;