<?xml version="1.0" encoding="<XDtConfig:configParameterValue paramName='Xmlencoding'/>"?>

<!DOCTYPE hibernate-configuration PUBLIC "<XDtXml:publicId/>" "<XDtXml:systemId/>">

<!-- File generated by vogen. Do not modify manually. -->

<hibernate-configuration>

	<session-factory>
		<#list resources as resource><mapping resource="${resource}"/>
    	</#list>
	</session-factory>

</hibernate-configuration>
