<@file name="hibernate.cfg.xml">
<?xml version="1.0" encoding="<XDtConfig:configParameterValue paramName='Xmlencoding'/>"?>

<!DOCTYPE hibernate-configuration PUBLIC "<XDtXml:publicId/>" "<XDtXml:systemId/>">

<!-- File generated by vogen. Do not modify manually. -->

<hibernate-configuration>

	<session-factory>
<@forAllTypes var="type" annotation="org.highway.database.MappedOn" includeInterfaces="true">
<mapping resource="${type.resourceHibernateFileName}"/>
</@forAllTypes>
	</session-factory>

</hibernate-configuration>
</@file>