<@file name="hibernate.cfg.xml">
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE hibernate-configuration PUBLIC
        "-//Hibernate/Hibernate Configuration DTD 3.0//EN"
        "http://hibernate.sourceforge.net/hibernate-configuration-3.0.dtd">

<!-- File generated by vogen. Do not modify manually. -->

<hibernate-configuration>

	<session-factory>
<@forAllTypes var="type" annotation="org.highway.database.Mapped" includeInterfaces="true">
<mapping resource="${type.resourceHibernateFileName}"/>
</@forAllTypes>
	</session-factory>

</hibernate-configuration>
</@file>