<@forAllTypes var="type" annotation="org.highway.annotation.VoMapping" includeInterfaces="true">
<@file name="${type.generatedShortClassName}.hbm.xml" package="${type.package.qualifiedName}">

<!DOCTYPE hibernate-mapping PUBLIC
	"-//Hibernate/Hibernate Mapping DTD 3.0//EN	"
    "http://hibernate.sourceforge.net/hibernate-mapping-3.0.dtd "
    >

<!-- File generated by vogen. Do not modify manually. -->
<hibernate-mapping>

    <class
    	name=${type.generatedClassName}
    	<@ifHasAnnotation var="ann" annotation="org.highway.annotation.VoMapping">
        table="${ann.value}"
        </@ifHasAnnotation>
        <@ifHasAnnotation var="ann" annotation="org.highway.annotation.VoMappingDiscriminatorValue">
        discriminator-value="${ann.value}"
        </@ifHasAnnotation>
     >
     	
     	<!--#if type.hasPrimitiveId-->
     	<@forAllMethods annotation="org.highway.annotation.VoMappingId" var="method" annotationVar="ann">
        <id
            name="${method.propertyName}"
            column="${ann.column}"
            type="${ann.type}">
        
            <generator class="${ann.generatorClass}">
            	<@forAllMethods declaration="type" annotation="org.highway.annotation.VoMappingGeneratorParam" var="generatorParamMethod" annotationVar="annGeneratorParam">
                <param name="${annGeneratorParam.name}">${annGeneratorParam.value}</param>
                </@forAllMethods>
            </generator>
        </id>
	    </@forAllMethods>
        

        
        <composite-id>
        	<@forAllMethods annotation="org.highway.annotation.VoMappingId" var="method" annotationVar="ann">
            <key-property
                name="${method.propertyName}"
                column="${ann.column}"
                type="${ann.type}"
            />
            </@forAllMethods>
        </composite-id>

        
        <@ifHasAnnotation var="ann" annotation="org.highway.annotation.VoMappingDiscriminator">
        <discriminator
                column="${ann.column}"
                type="${ann.type}"
                force="${ann.force}"
                insert="${ann.insert}"
        />
        </@ifHasAnnotation>
        <@forAllMethods annotation="org.highway.annotation.VoMappingProperty" var="method" annotationVar="ann">
        <property 
            name="${method.propertyName}"
            type="${ann.type}"
            column="${ann.column}"
            insert="${ann.insert}"
            update="${ann.update}"
        />
        </@forAllMethods>
	</class>
	
	<@ifHasAnnotation var="ann" annotation="org.highway.annotation.VoMappingDiscriminatorValue">
    <subclass
        name="${method.entityClassName}"
        extends="${method.superClassName}"
        discriminator-value="${ann.value}"
    >
   
       <@forAllMethods annotation="org.highway.annotation.VoMappingProperty" var="method" annotationVar="ann">
        <property
            name="${method.propertyName}"
            type="${ann.type}"
            column="${ann.column}"
            insert="${ann.insert}"
            update="${ann.update}"
        />
       </@forAllMethods>
      </subclass>
    </@ifHasAnnotation>
   
	<@ifHasAnnotation var="ann" annotation="org.highway.annotation.VoMappingDiscriminator">
    <joined-subclass
        name="${method.entityClassName}"
        extends="${method.superClassName}"
    	<@ifHasAnnotation var="annMapping" annotation="org.highway.annotation.VoMapping">
        table="${annMapping.value}"
        </@ifHasAnnotation>
    >

       <!--key column="${helper.keyColumn}"/-->

       <@forAllMethods annotation="org.highway.annotation.VoMappingProperty" var="method" annotationVar="ann">
        <property
            name="${method.propertyName}"
            type="${ann.type}"
            column="${ann.column}"
            insert="${ann.insert}"
            update="${ann.update}"
         />
       </@forAllMethods>
      
    </joined-subclass>
   </@ifHasAnnotation>
	
</hibernate-mapping>
</@file>
</@forAllTypes>