<@forAllTypes var="type" annotation="org.highway.annotation.VoMapping" includeInterfaces="true">
<@file name="${type.generatedShortClassName}.hbm.xml" package="${type.package.qualifiedName}">

<!DOCTYPE hibernate-mapping PUBLIC
	"-//Hibernate/Hibernate Mapping DTD 3.0//EN	"
    "http://hibernate.sourceforge.net/hibernate-mapping-3.0.dtd "
    >

<!-- File generated by vogen. Do not modify manually. -->
<hibernate-mapping>
	<#if type.ifIsClass>
    <class
     	name="${type.generatedClassName}"
    	<@ifHasAnnotation var="ann" annotation="org.highway.annotation.VoMapping">
        table="${ann.table}"
        </@ifHasAnnotation>
        <@ifHasAnnotation var="ann" annotation="org.highway.annotation.VoMappingDiscriminatorValue">
        discriminator-value="${ann.value}"
        </@ifHasAnnotation>
     >
     	
     	<#if type.hasPrimitiveId>
     	<@forAllMethods annotation="org.highway.annotation.VoMappingId" var="method" annotationVar="ann">
        <id
            name="${method.propertyName}"
            column="${ann.column}"
            type="<@annotationValue declaration=method annotation="org.highway.annotation.VoMappingPropertyType" default=${method.returnType}/>"
            <generator class="${ann.generatorClass}">
			<@forAllMethods declaration=type annotation="org.highway.annotation.VoMappingGeneratorParam" var="generatorMethod" annotationVar="annGenerator">
			<param name="${annGenerator.name}">${annGenerator.value}</param>
			</@forAllMethods>
            </generator>
        </id>
	    </@forAllMethods>
        <#elseif type.hasCompositeId>
        <composite-id>
        	<@forAllMethods annotation="org.highway.annotation.VoMappingId" var="method" annotationVar="ann">
            <key-property
                name="${method.propertyName}"
                column="${ann.column}"
                type="<@annotationValue declaration=method annotation="org.highway.annotation.VoMappingPropertyType" default="${method.returnType}"/>"
            />
            </@forAllMethods>
        </composite-id>
		</#if>
        
        <@ifHasAnnotation var="ann" annotation="org.highway.annotation.VoMappingDiscriminator">
        <discriminator
                column="${ann.column}"
                type="<@annotationValue declaration=method annotation="org.highway.annotation.VoMappingPropertyType" default="${method.returnType}"/>"
                force="${ann.force}"
                insert="${ann.insert}"
        />
        </@ifHasAnnotation>
        <@forAllMethods annotation="org.highway.annotation.VoMappingProperty" var="method" annotationVar="ann">
        <property 
            name="${method.propertyName}"
            type="<@annotationValue declaration=method annotation="org.highway.annotation.VoMappingPropertyType" default="${method.returnType}"/>"
            column="${ann.column}"
            insert="${ann.insert}"
            update="${ann.update}"
        />
        </@forAllMethods>
	</class>
	<#elseif type.ifIsSubClass>
    <subclass
        name="${type.entityClassName}"
        extends="${type.superClassName}"
        <@ifHasAnnotation var="ann" annotation="org.highway.annotation.VoMappingDiscriminatorValue">
        discriminator-value="${ann.value}"
        </@ifHasAnnotation>
    >
   
       <@forAllMethods annotation="org.highway.annotation.VoMappingProperty" var="method" annotationVar="ann">
        <property
            name="${method.propertyName}"
            type="<@annotationValue declaration=method annotation="org.highway.annotation.VoMappingPropertyType" default="${method.returnType}"/>"
            column="${ann.column}"
            insert="${ann.insert}"
            update="${ann.update}"
        />
       </@forAllMethods>
      </subclass>

   	<#elseif type.ifIsJoinedSubClass>
    <joined-subclass
        name="${type.entityClassName}"
        extends="${type.superClassName}"
    	<@ifHasAnnotation var="annMapping" annotation="org.highway.annotation.VoMapping">
        table="${annMapping.table}"
        </@ifHasAnnotation>
    >
		<key column="<@annotationValue declaration=method annotation="org.highway.annotation.VoMappingKeyColumn" default="${type.keyColumn}"/>"/>

       <@forAllMethods annotation="org.highway.annotation.VoMappingProperty" var="method" annotationVar="ann">
        <property
            name="${method.propertyName}"
            type="<@annotationValue declaration=method annotation="org.highway.annotation.VoMappingPropertyType" default="${method.returnType}"/>"
            column="${ann.column}"
            insert="${ann.insert}"
            update="${ann.update}"
         />
       </@forAllMethods>
      
    </joined-subclass>
	</#if>
</hibernate-mapping>
</@file>
</@forAllTypes>