drop table highway.MAPPING_TEST;
drop table highway.TRIM_TEST;

create table highway.MAPPING_TEST (
	TYPE_PRIMITIVE_LONG BIGINT not null,
	TYPE_PRIMITIVE_BOOLEAN CHAR not null,
	TYPE_PRIMITIVE_CHAR CHAR not null,
	TYPE_PRIMITIVE_DOUBLE INTEGER not null,
	TYPE_PRIMITIVE_FLOAT INTEGER not null,
	TYPE_PRIMITIVE_INT INTEGER not null,
	TYPE_PRIMITIVE_SHORT INTEGER not null,
	TYPE_LONG BIGINT,
	TYPE_BOOLEAN CHAR,
	TYPE_CHARACTER CHAR,
	TYPE_DOUBLE INTEGER,
	TYPE_FLOAT INTEGER,
	TYPE_INTEGER INTEGER,
	TYPE_SHORT INTEGER,
	TYPE_STRING VARCHAR(20),
	TYPE_SQL_DATE DATE,
	TYPE_UTIL_DATE TIMESTAMP,
	TYPE_TIME TIME,
	TYPE_TIMESTAMP TIMESTAMP,
	TYPE_BIG_DECIMAL DECIMAL(10,2),
	TYPE_BIG_INTEGER DECIMAL(10,2),
	TYPE_DECIMAL DECIMAL(10,2),
	TYPE_CHAR_ENUM CHAR,
	TYPE_SHORT_ENUM INTEGER,
	TYPE_STRING_ENUM CHAR(2),
	TYPE_BLOB blob(100),
	primary key (TYPE_PRIMITIVE_LONG)
);

create table highway.TRIM_TEST (
	ID BIGINT not null,
	PROPERTY_1 CHAR(20),
	PROPERTY_2 CHAR(20),
	PROPERTY_3 CHAR(20),
	primary key (ID)
);

commit;