"/*
 * File generated by vogen. Do not modify manually.
 */"

package ${declaration.package.qualifiedNAme};

"import org.highway.helper.ValueHelper;
import org.highway.vo.ValueObjectAbstract;"
public class ${declaration.generatedShortClassName()}
	extends ${declaration.superClassName()}
	implements ${declaration.declaration.getQualifiedName()}