<@file name="ejb-jar.xml">
<?xml version="1.0" encoding="<XDtConfig:configParameterValue paramName='Xmlencoding'/>"?>

<!DOCTYPE ejb-jar PUBLIC
	"-//Sun Microsystems, Inc.//DTD Enterprise JavaBeans 2.0//EN"
	"http://java.sun.com/dtd/ejb-jar_2_0.dtd">

<!-- File generated by ejbgen. Do not modify manually. -->

<ejb-jar id="ejb-jar_ID">

   <enterprise-beans>

      <!-- session beans -->
<@forAllTypes var="bean" annotation="org.highway.annotation.GenerateEjb" includeInterfaces="true">
      <session id="${bean.simpleName}">
         <ejb-name>${declaration.beanFullClassName}</ejb-name>
         <home>${declaration.homeFullClassName}</home>
         <remote>${declaration.remoteFullClassName}</remote>
         <ejb-class>${declaration.beanFullClassName}</ejb-class>
         <session-type>Stateless</session-type>
         <transaction-type>Bean</transaction-type>
      </session>

</@forAllTypes>
   </enterprise-beans>

</ejb-jar>
</@file>