/*
 * File generated by ejbgen. Do not modify manually.
 */
 
package ${declaration.packageName}.ejb;

import java.rmi.RemoteException;
import javax.ejb.CreateException;
import javax.ejb.EJBHome;

/**
 * File generated by ejbgen. Do not modify manually.
 */
public interface ${declaration.generatedShortClassName}EjbHome extends EJBHome
{
	public ${declaration.generatedShortClassName}EjbRemote create() throws CreateException, RemoteException;
}