<!-- File generated by ejbgen. Do not modify manually. -->

<ejbbnd:EJBJarBinding
   xmi:version="2.0"
   xmlns:xmi="http://www.omg.org/XMI" xmlns:ejbbnd="ejbbnd.xmi"
   xmlns:ejb="ejb.xmi" xmlns:commonbnd="commonbnd.xmi"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmi:id="ejb-jar_ID_Bnd">

   <ejbJar href="META-INF/ejb-jar.xml#ejb-jar_ID"/>

<#list declaration.sessionBeans as bean>
   <ejbBindings xmi:id="${bean.simpleName}_Binding" jndiName="${declaration.homeJNDIName(bean)}">
      <enterpriseBean xmi:type="ejb:Session" href="META-INF/ejb-jar.xml#${bean.simpleName}"/>

   <XDtClass:ifHasClassTag tagName="websphere:datasource" paramName="jndi-name">
         <datasource
            xmi:id="<XDtId:prefixedId prefix='Datasource' wrapInIdEquals='false'/>"
            jndiName="<XDtClass:classTagValue tagName='websphere:datasource' paramName='jndi-name'/>">
            <defaultAuth
               xmi:type="commonbnd:BasicAuthData"
               xmi:id="<XDtId:prefixedId prefix='BasicAuthData' wrapInIdEquals='false'/>">
               <userId xsi:nil="true"/>
               <password xsi:nil="true"/>
            </defaultAuth>
         </datasource>
   </XDtClass:ifHasClassTag>
   </ejbBindings>

</#list>

<XDtConfig:ifHasConfigParam paramName="DefaultDatasource">
     <defaultDatasource
        xmi:id="<XDtId:prefixedId prefix='Datasource' wrapInIdEquals='false'/>"
        jndiName="<XDtConfig:configParameterValue paramName="DefaultDatasource"/>">
        <defaultAuth
           xmi:type="commonbnd:BasicAuthData"
           xmi:id="<XDtId:prefixedId prefix='BasicAuthData' wrapInIdEquals='false'/>">
           <userId xsi:nil="true"/>
           <password xsi:nil="true"/>
        </defaultAuth>
     </defaultDatasource>
</XDtConfig:ifHasConfigParam>

</ejbbnd:EJBJarBinding>
