<@forAllTypes var="type" includeInterfaces="true">
<@javaSource name="${type.package.qualifiedName}.ejb.${type.generatedShortClassName}EjbRemote">

/*
 * File generated by ejbgen. Do not modify manually.
 */

package ${type.package.qualifiedName}.ejb;

import javax.ejb.EJBObject;

/**
 * File generated by ejbgen. Do not modify manually.
 */
public interface ${type.generatedShortClassName}EjbRemote extends EJBObject
{
<@forAllMethods var="method">
	public ${method.returnType} ${method.simpleName}(${method.parametersDeclaration})
		${method.exceptionsDeclaration("java.rmi.RemoteException")};
</@forAllMethods>
}
</@javaSource>
</@forAllTypes>