<@forAllTypes var="type" annotation="org.highway.service.ejb.GenerateEjb" includeInterfaces="true">
<@javaSource name="${type.package.qualifiedName}.ejb.${type.generatedShortClassName}EjbRemote">

/*
 * File generated by ejbgen. Do not modify manually.
 */

package ${type.package.qualifiedName}.ejb;

import javax.ejb.EJBObject;

/**
 * File generated by ejbgen. Do not modify manually.
 */
public interface ${type.generatedShortClassName}EjbRemote extends EJBObject
{
<@forAllMethods var="method">
	public ${method.returnTypeQualifiedName} ${method.simpleName}(${method.parametersDeclaration})
		${method.exceptionsDeclarationWithRemoteException};
</@forAllMethods>
}
</@javaSource>
</@forAllTypes>