/*
 * File generated by ejbgen. Do not modify manually.
 */

package ${declaration.packageName}.ejb;

import javax.ejb.EJBObject;

/**
 * File generated by ejbgen. Do not modify manually.
 */
public interface ${declaration.generatedShortClassName}EjbRemote extends EJBObject
{
<#list declaration.methods as method>

	public ${method.returnType} ${method.simpleName}(${declaration.getParametersDeclaration(method)})
		${declaration.getExceptionsDeclaration(method, "java.rmi.RemoteException")};
</#list>
}
